### ISSUE TITLE
Questions about the lineage curves: colors & extracting

### ISSUE THREAD

**Issue by SimoniMD** [HectorRDB/condiments#15]
Hi! thanks for the package. i got my lineage curves to work, but they are kinda hard to see due to the colors:
```
for (condition in c("IFN", "Control")) {
  sds2_cond <- sdss2[[condition]]
  for (i in 1:2) {
    p4 <- p4 + 
      geom_path(data = slingCurves(sds2_cond)[[i]]$s[slingCurves(sds2_cond)[[i]]$ord, ] %>%
                  as.data.frame() %>%
                  mutate(condition = condition),
                size = 1.5)
  }
}
```

![image](https://user-images.githubusercontent.com/82599359/163091033-8e8b096f-7cdc-4b2d-b823-8ceca2a79321.png)

![image](https://user-images.githubusercontent.com/82599359/163089201-81428c5c-8cc7-4d38-849b-ba5fe0b8df01.png)

If i change the colors in the geom_path, it creates the same color for the same lineage, instead of the same condition:
```for (condition in c("IFN", "Control")) {
  sds2_cond <- sdss2[[condition]]
  for (i in 1:2) {
    p4 <- p4 + 
      geom_path(data = slingCurves(sds2_cond)[[i]]$s[slingCurves(sds2_cond)[[i]]$ord, ] %>%
                  as.data.frame() %>%
                  mutate(condition = condition),
                size = 1.5,
                colour = colorsequence2[i])
  }
}
```
![image](https://user-images.githubusercontent.com/82599359/163091591-a80652d8-217f-4414-b44b-a03e5860bd22.png)

I'm trying to get the condition to be the same color, not the lineage. Would also like them to be a different color than the points. Thoughts?

On a related, but similar note...i tried to work around by extracting the curve to put it onto another UMAP, but I couldn't figure this out. Any way you can think of to do that?

**Comment by HectorRDB** [comment]
Hi @SimoniMD 
Thanks for using condiments.
If you want to change the colors, you should add
``` 
scale_color_manual(values = c("Control" = color1, "IFN" = color2))
```

As for the other question, I don't think I understand. Trajectory inference is dependent on a specific dimensionality reduction, the curves only exist in that space.

**Comment by SimoniMD** [comment]
Thank you for the help! i meant literally taking off the layer and putting it over something not as colorful. i actually was able to do it with ggedit and the color help you provided:
![testPicture1](https://user-images.githubusercontent.com/82599359/163821792-ad931f58-ef0d-4245-af32-3db4402e54e5.png)

**Comment by HectorRDB** [comment]
Thanks @SimoniMD .
Do you mind sharing that code below so that others can benefit?

**Comment by HectorRDB** [comment]
Closed due to inactivity.
