### ISSUE TITLE
unable to install Ecume 

### ISSUE THREAD

**Issue by zara03** [HectorRDB/condiments#21]
i am facing issues in installing condiments.
I am unable to install Ecume code i used is

if(!requireNamespace("BiocManager", quietly = TRUE)) {
install.packages("BiocManager")
}
BiocManager::install("Ecume")
Error in readRDS(dest) : error reading from connection
i also tried with
devtools::install_github("HectoRDB/Ecume")
Error: Failed to install 'unknown package' from GitHub:
HTTP error 404.
Not Found

Did you spell the repo owner (HectoRDB) and repo name (Ecume) correctly?

If spelling is correct, check that you have the required permissions to access the repo.
Can you please tell me what to do?

**Comment by HectorRDB** [comment]
Hi.
Is the error still occuring?

**Comment by HectorRDB** [comment]
The spelling is incorrect and should be 
```
devtools::install_github("HectorRDB/Ecume")
```
