### ISSUE TITLE
conditionTest log2FC

### ISSUE THREAD

**Issue by flde** [HectorRDB/condiments#22]
Dear condiments team, 

Many thanks for the great pre-print and tutorials. I was just wondering about the meaning of the log2FC argument of the conditionTest which tests the null hypothesis that the smoother are identical across conditions. In my understanding the conditionTest compares the smoother parameter rather than expression values? 

I checked the function description and pre-preprint methods but fail to understand the meaning of the log2FC threshold. 

Many thanks for your help!

Best wishes, 
Florian

**Comment by HectorRDB** [comment]
Hi,
Indeed, we compare the smoother parameters, but those are directly linked to log2FC via the modelling. The conditionTest actually contrasts the smoothers for different condittions along the trajectory.

**Comment by flde** [comment]
Many thanks @HectorRDB! I will have another look at the methods since I obviously lack some important understanding. All the very best, Florian.
