### ISSUE TITLE
Using condiments on ctrl treatment data from two time points

### ISSUE THREAD

**Issue by Rohit-Satyam** [HectorRDB/condiments#25]
Hi 

I have single cell data from two time points T1 and T2. Each time point contains control and treatment sample. We perform integration with Seurat using a single cell atlas as reference and then remove the reference atlast data once we obtain UMAP. Then we use UMAp to run slingshot to get primary trajectory. I came across a tutorial of your paper and I wish to use condiments package. Would u suggest running condiments together on T1 and T2 or should I separate them into two singlecellexperiment object and then run condiment on them? How can I give condiment information about my experimental time points? Also should I club controls from both time points as a single "control" and vice versa for treatment to calculate imbalance scores?

**Comment by HectorRDB** [comment]
Hi,
I would generally recommand merging time points T1 and T2, as you are more likely to compare the full trajectory this way.
Batch effect can be addressed in your reduced dimensionality method. 

You should thus use control from two time points, and some for tttt. 

If the batch effects are too strong, you can do the following, after updating to use the latest version of condiments:
- the topologyTest can be run on each batch, to check the results
- You can add the timepoint info in the fitGam function as well.
Hope this helps

**Comment by HectorRDB** [comment]
Closed because of inactivity.
