### ISSUE TITLE
Theory Basis of Differential Progression

### ISSUE THREAD

**Issue by GilbertHan1011** [HectorRDB/condiments#27]
Hello, the Differential Progression section is quite intriguing. I'm curious whether this section has a theoretical foundation; from what I've come across, population balance analysis seems relevant. Are there similar tools or approaches associated with Differential Progression?

**Comment by HectorRDB** [comment]
Hello,
By theory, do you mean it in a mathematical or biological sense ? 

Regarding background for this idea (and the fateSelection section as well), the main idea is that we are comparing uni and multi-dimensional distribution in a non-parametric fashion (the distribution of cells in the latent space). Intepretation of those results can be quite hard: focusing on the distribution of pseudotime and cell weights as separate variables allow to give more interpretable results. 

I hope this helps

**Comment by GilbertHan1011** [comment]
I am referring to the biological significance. What I mean is that I believe the variation of cell abundance along pseudotime is meaningful. In your example, differences in abundance under different conditions may indicate differences in differentiation rates. However, cell abundance may also be associated with sampling locations, tissue processing methods, sequencing machines, and even data preprocessing. Moreover, what kind of relationship exists between differentiation rates and cell abundance? I haven't seen any literature exploring this aspect. Therefore, I would like to know your opinion.

**Comment by HectorRDB** [comment]
Thanks for clarifying.
Indeed, the differences between the conditions could come from many differences that are more or less relevant. What we can get from the data is only the fact that we see differential abundance between conditions. It is then up to the biologist to investigate the why; although I do believe that having a better understanding of what is differentially abundant will help.

Regarding examples, I will refer you to the first case study on our paper. The condition under the growth factor TGF-B differentiate faster than the control. However, I unfortunately cannot provide a good reference for a more comprehensive overview of the phenomenon.

I hope this answers your question.

**Comment by GilbertHan1011** [comment]
Thanks!
