### ISSUE TITLE
Trajectory inference multiple conditions

### ISSUE THREAD

**Issue by dhivyaa-6** [HectorRDB/condiments#3]
I followed the analysis of the kras dataset and implementing the same for a multi-condition (5 conditions) trajectory inference. I have issues in the step

 sds <- do.call(merge_sds, sdss)
Where I get the error Error in (function (..., mapping, condition_id = seq_len(ncol(mapping)), :
Some lineages are not mapped

However it works when I try for 2 conditions. Is there something am missing while analyzing 5 conditions at the same time? I also tried for 3 and did not work. I went through the reference manual for the merge_sds function and still get the same error.

**Comment by HectorRDB** [comment]
Hi @dhivyaa-6 
There is no reasons, i should not work for 5 conditions. However, given the error message, I think it comes from the fact that some of the trajectories do not have all lineages.

Did you check that? Alternatively, you can provide the mapping matrix yourself as well.
Best

**Comment by HectorRDB** [comment]
Closing after a month of inactivity. Feel free to re-open if the issue persists

**Comment by AndreaYCT** [comment]
Hi, @HectorRDB 

I have encountered same issue "> sds <- do.call(merge_sds, sdss)
Error in (function (..., mapping, condition_id = seq_len(ncol(mapping)),  : 
  Some lineages are not mapped"

I have 4 conditions (3 samples, 3 samples, 3 samples, and 2 samples/condition) and i have. 9 lineages in the sdss. And there are 9 lineages in each condition (pathnames(9): Lineage1 Lineage2 ... Lineage8 Lineage9)

How to edit the codes?

Thank you in advance!

Andrea
