### ISSUE TITLE
Following vignette, no condimentsPaper package

### ISSUE THREAD

**Issue by chungsai** [HectorRDB/condiments#31]
https://hectorrdb.github.io/condimentsPaper/articles/KRAS.html

kras <- condimentsPaper::import_KRAS()

Error in loadNamespace(x) : there is no package called ‘condimentsPaper’

data("kras", package = "condimentsPaper")

Error in find.package(package, lib.loc, verbose = verbose) : 
  there is no package called ‘condimentsPaper’

**Comment by HectorRDB** [comment]
Hello, 
You need to install the condimentsPaper package from github 
```
if(!requireNamespace("devtools", quietly = TRUE)) {
 install.packages("devtools") 
}
devtools::install_github("HectorRDB/condimentsPaper")
```
