### ISSUE TITLE
Discussion: When two trajectories are needed

### ISSUE THREAD

**Issue by MartaSanchezCarbonell** [HectorRDB/condiments#32]
Dear Hector, 
First of all, I would like to congratulate you for your package and for your paper, it is an amazing work. I would like to open a discussion with you about how to interpret some results when the data (having a WT and a KO group) shows enough differences to infer two different trajectories.
I started by calculating the imbalance score (see the UMAP) and running the topology test (p-value= 0.0000134). 
 
![image](https://github.com/HectorRDB/condiments/assets/106607855/b193edc6-0692-4a04-ab3f-be31caa656fb)

As you can see, it indicated that my data was different enough to calculate two trajectories, specifically in the upper part of the UMAP. In order to continue with my analysis I followed your tutorials, specifically the one for the KRAS dataset (https://hectorrdb.github.io/condimentsPaper/articles/KRAS.html#references-1) as it was showing the most similar situation to my situation. 
Then, I calculated the trajectories for each condition:
  
![image](https://github.com/HectorRDB/condiments/assets/106607855/68ea6b1c-8560-4e57-b42a-63adeb58c95f)
![image](https://github.com/HectorRDB/condiments/assets/106607855/f9b80cc5-3d12-429b-855c-bf62b8c48c87)

As expected, the major differences are present in the upper part of the UMAP (coloured in a darker colour and which comprises the less differentiated state of this cell type) even showing a different origin. As a consequence, when I plot the distribution of the different age groups that are forming this dataset along pseudotime the part of the UMAP coloured in a lighter colour, which comprises the adult state of this cell type, appears shifted, despite of having a similar ending point. 
 
![image](https://github.com/HectorRDB/condiments/assets/106607855/b7fa7b4c-7160-4707-9e51-425056186e86)

What could I do to compare them? I thought about shifting all the pseudotime values of the WT group so that they have the same final point when it comes to pseudotime values, but I am not sure if this is correct (see example below):
 
![image](https://github.com/HectorRDB/condiments/assets/106607855/06ea1e3b-152f-4283-9669-1f1ef79909e9)

Could you advise me on my situation?
Thank you very much in advance :)

Marta

**Comment by HectorRDB** [comment]
Hi,

I think in your case, the issue stems from a lack of resolution in terms of number of clusters. With only two clusters, the actual start point of the trajectory in the black cluster is unclear. If you have more resolution, the test should recommend fitting one trajectory. 

As a side note, we now recommend not using UMAP coordinates as an input for slingshot, but to use PCA or scVI latent space.

Let me know if that help or if you have further questions,
