### ISSUE TITLE
assigning a lineage

### ISSUE THREAD

**Issue by cristanchoa** [HectorRDB/condiments#7]
Hello, 

Thanks for building this program! Looks very powerful. I have a basic question about the "lineages" assignment. I am trying to compare two cell types in a dataset I have treated with hypoxia. The comparisons I'd like to make are between the conditions in each cell type. I've been following the tgfb vignette which gets close to what I'd like to do, but not quite. 

I had tried the progression test but I'm not quite sure what the assignment of each lineage is corresponding too. 
>progressionTest(SlingshotDataSet(glut1_npc_sce1), conditions = glut1_npc_sce1$celltype.condition, lineage = TRUE)
  lineage statistic       p.value
1     All 0.9384452  0.000000e+00
2       1 0.8938462 3.358798e-128
3       2 0.5573077  2.307548e-11

Thanks in advance for any advice!
Ana

**Comment by HectorRDB** [comment]
Closing after a month of inactivity. Please do not hesitate to reopen if the issue persists.
